language: node_js
node_js:
  - "node"
  - "6"
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
notifications:
  email:
    on_success: never
    on_failure: always
